:imagesdir: figs/
:stem:

= Modèle mémoire Rust: propriété et emprunts 

== Objectifs

L'innovation majeure de Rust est son modèle mémoire qui combine:

- des vérifications statiques qui permettent de détecter les problèmes mémoire
- des abstractions à coût nul qui permettent de générer un code efficace

Nous allons étudier les notions que Rust introduit pour garantir que les programmes sont corrects en mémoire, en particulier les notions de _Propriété_ (Ownership) et _Emprunt_ (Borrow).

== Mutabilité 

- Par défaut les variables sont immutables

[source, rust]
----
    let a = 1;
    let mut b = 1;
    a = 2; // erreur: Cannot assign twice to immutable variable a
    b = 2; // ok
----

== Les variables locales sont allouées sur la pile

[source, rust]
----
fn main() {
    let a : u32 = 1;
    let b : f32 = 3.1415;
    let c : [u32; 3] = [1, 2, 3];
    let d = [0; 1 << 30]; // tableau avec 2^30 zéros => débordement de pile 
}
----

- Les types primitifs de Rust sont alloués sur la pile.

== Allocation sur le tas

- Rust permet aussi d'allouer dynamiquement des objets sur le tas.
- Par exemple, les vecteurs de type +Vec<T>+ sont alloués sur le tas.
[source, rust]
----
let v : Vec<u32> = vec![1,2,3]; // <1>
----
<1> Ici +v+ est une variable locale (sur la pile) qui contient un pointeur vers une adresse du tas où l'objet +Vec<u32>+ est alloué.

== Propriétaire

Pour toute donnée, rust définit une variable _propriétaire_.

IMPORTANT: À tout moment il ne peut y avoir qu'un et un seul propriétaire. 

[source, rust]
----
fn test() {
    let a = 1.0; //<1>
    let v = vec![1,2,3]; //<2>
    // fin du bloc <3>
}
----
<1> +a+ est propriétaire du scalaire
<2> +v+ est propriétaire du vecteur
<3> En fin de bloc +a+ et +v+ sont _hors-portée_. Leur mémoire est automatiquement libérée par rust. Le flottant 1.0 est dépilé et le vecteur désalloué avec un appel à +.drop()+.

== Trait +Copy+

- Les types primitifs (alloués sur la pile) implémentent le trait +Copy+.

- Lors d'une affectation, les données d'un type avec le trait +Copy+ sont
copiés.

- Chaque variable est l'unique propriétaire de sa propre copie. L'invariant de « propriété unique » est satisfait.

[source, rust]
----
fn main() {
    let a = [1, 2, 3];
    let mut b = a; // les trois cases du tableau sont copiées
    b[1] = 5;
    assert_eq!(a[1], 2); // a n'est pas modifié
    assert_eq!(b[1], 5); // seul b est modifié
}
----

== Passage par valeur

- De même lors d'un appel de fonction, les types primitifs sont copiés.

[source, rust]
----
fn modify(mut tab : [u32; 3]) {
    tab[1] = 4; // c'est la copie locale tab qui est modifiée
}

fn main() {
    let mut a = [1, 2, 3]; // (a n'a pas besoin d'être mutable)
    modify(a); //l'argument passé par valeur (copie)
    assert_eq!(a[1], 2); // a n'est pas modifié
}
----

== Transfert de propriétaire (affectation)

- Pour les types qui n'implementent pas le trait +Copy+, une affectation déplace la propriété vers une nouvelle variable.

[source, rust]
----
    let v1: Vec<u32> = vec![1, 2, 3]; // v1 est propriétaire du vecteur
    let v2 = v1; // la propriété est transférée à v2
    println!("{}", v1[0]); // erreur: ne peut plus être utilisé
    // erreur: borrow of moved value v1
----

== Tranfert de propriétaire (appel de fonction) 

- Même problème lors d'un appel de fonction, la propriété est transférée.

[source, rust]
----
fn fun(v : Vec<u32>) { ... }

fn main() {
    let v1: Vec<u32> = vec![1, 2, 3]; // v1 est propriétaire du vecteur
    fun(v1); // la propriété est transférée à l'argument v 
    println!("{}", v1[0]); // erreur: borrow of moved value v1
}
----

== Erreurs mémoire évitées par le transfert
[source, c]
----
#include <stdlib.h>
void fun(char * v) {
  free(v);
}

int main() {
  char * v1 = malloc(3);
  fun(v1);
  free(v1); // <1>
}
// free(): double free detected in tcache 2
// Aborted (core dumped)
----
<1> Erreur en C à l'exécution. Impossible en Rust, car +v1+ n'est plus propriétaire de la mémoire.  

== Comment appeler une fonction sans perdre la propriété ?

[source, rust]
----
fn print(v: Vec<u32>) -> Vec<u32> {
    println!("{:?}", v);
    v // on retourne l'objet v pour transférer la propriété en retour
}

fn main() {
    let v1: Vec<u32> = vec![1, 2, 3]; // v1 est propriétaire du vecteur
    let v1 = print(v1); // l'appel cède puis récupère la propriété.
    assert_eq!(v1[0], 1); // l'accès à v1[0] est possible 
}
----

WARNING: Le code ci-dessus est correct mais pas idiomatique. C'est fastidieux de devoir passer la propriété en retour pour de nombreuses variables.

== Emprunts

- Un emprunt permet de passer une référence à un objet sans en céder la propriété.

[source, rust]
----
fn print(v: &Vec<u32>) { // la fonction travaille sur un emprunt elle n'est
    println!("{:?}", v); // pas propriétaire du vecteur.
}

fn main() {
    let v1: Vec<u32> = vec![1, 2, 3]; // v1 est propriétaire du vecteur
    print(&v1); // on emprunte une référence sur le vecteur
    assert_eq!(v1[0], 1);
}
----

== Emprunts mutables

- Par défault les emprunts sont immutables. Pour pouvoir modifier l'objet emprunté, il nous faut un type +& mut+

[source, rust]
----
fn fun(v: &mut Vec<u32>) {
    v.push(4);
}

fn replace(v: &mut Vec<u32>) {
    *v = vec![4,5]; // pour modifier le contenu il faut utiliser l'opérateur *
}

fn main() {
    let mut v1: Vec<u32> = vec![1, 2, 3];
    fun(&mut v1); // on emprunte une référence mutable sur le vecteur
    assert_eq!(v1[3], 4);
    replace(&mut v1);
    assert_eq!(v1.len(), 2);
}
----

== Emprunts mutables ≠ Transfert de propriété

- Un emprunt mutable n'est pas équivalent à un transfert de propriété
- Par exemple, il n'est pas possible de désallouer une référence mutable 😊

[source, rust]
----
fn fun(v: &mut Vec<u32>) {
    drop(*v); // erreur: cannot move out of *v which is behind a mutable reference 
}
fn main() {
    let mut v1: Vec<u32> = vec![1, 2, 3];
    fun(&mut v1); // on emprunte une référence mutable sur le vecteur
}
----

== Les trois règles des emprunts

. Les emprunts ne peuvent pas avoir une durée de vie plus longue que celle du propriétaire.

À un point dans le programme, il est possible d'emprunter:

[start=2]
. une ou plusieurs références +&T+ 
. exactement une seule référence mutable +&mut T+

== Exemple: erreur évitée avec la règle (1) 

- Rust nous interdit de retourner une référence sur x car il ne peut pas
garantir que sa durée de vie est suffisante.

[source, rust]
----
fn fun() -> &u32 { // erreur: missing lifetime specifier
    let x = 1;
    &x
}

fn main() {
    let y : &u32 = fun();  
}
----

- En effet la mémoire de x, sur la pile, est libérée en sortie de fonction
- En C, ceci est une source d'erreurs classique !

== Exemple: erreur évitée avec les règles (2) et (3) 

[source, rust]
----
fn main() {
    let mut v = vec![1, 2, 3, 4];

    rayon::join( // on lance deux threads concurrents
        || {
            v[0] = 5; // premier thread
        },            
        // erreur: cannot borrow `v` as mutable more than once at a time
        || { 
            v[0] = 4; // deuxième thread
        },
    );
}
----

- Évite les problèmes d'accès concurrents. Ici les deux threads voudraient modifier le même tableau. 
- Rust l'interdit car v est emprunté deux fois de manière mutable.

== Références

- https://doc.rust-lang.org/1.22.0/book/second-edition/[The Rust book, first and second editions]
- http://cis198-2016s.github.io/[CIS 198 U. Pennsylvania: Rust programming lectures]
- https://stanford-cs242.github.io/f18/lectures/05-1-rust-memory-safety.html[Memory safety in Rust]
