:imagesdir: figs/
:stem:

= Rust: Types composites et constructions spécifiques

== Chaînes de caractères

- Il existe deux types en Rust pour représenter les chaînes.
** `String` pour une chaîne allouée dynamiquement sur le tas.
** `&str` pour une référence vers une chaîne de taille fixe. &str est appellé une _slice_ (partie) de chaîne.
- Les chaînes littérales (`"Hello World!"`) retournent un `&str` vers une zone de mémoire statique.

== Chaînes: exemple

[source, rust]
----
let s1: &str = "Hello World!"; // alloué à la compilation
let mut s2: String = String::from("Bye bye"); // alloué dynamiquement sur le tas
s2.push('!'); //s2 est mutable
let s3: &str = &s2[4..];
println!("{}", s3); // affiche: bye!
----

== Les vecteurs

- Pour représenter un tableau de valeurs, Rust propose le type `Vec<T>`
- Les vecteurs sont alloués dynamiquement sur le tas.

[source, rust]
----
let mut v: Vec<i32> = Vec::new();
v.push(5);
v.push(6);
v.push(7);

let w: Vec<i32> = vec![5, 6, 7]; //macro équivalent
----

== Accéder aux éléments d'un vecteur

[source, rust]
----
let mut v = vec![1, 2, 3, 4, 5];

let x: &i32 = &v[2]; // panique si l'index n'existe pas

match v.get(2) {
    Some(y) => println!("v[3] == {}", y),
    None => println!("index non-existant")
}

v[2] = 42; // car le vecteur v est mutable
----

== Itérer sur un vecteur

[source, rust]
----
let mut v = vec![1, 2, 3, 4, 5];

// itération non-mutable, i est de type &i32
for i in &v {
    println!("{}", i);
}

// itération mutable, i est de type &mut i32
// on peut incrémenter chaque élément du vecteur
for i in &mut v {
    *i += 1;
}
----

== Structures

- Une structure est un type composite composé de membres

[source, rust]
----
struct Personne {
    nom: String,
    année_naissance: i32,
}

let mut ada = Personne {
    nom : String::from("Ada Lovelace"),
    année_naissance: 0,
};

println!("nom = {}", ada.nom);
ada.année_naissance = 1815;
----

== Constructeur

- On appelle _constructeur_ une fonction qui retourne une instance de la structure.
- Dans le cours suivant nous verrons comment associer directement des méthodes à une structure.

[source, rust]
----
fn nouvelle_personne(nom: String, année: i32) -> Personne {
    Personne {
        année_naissance: année,
        nom, // sucre syntaxique
    }
}
----

== Tuples
- Les tuples sont un cas particulier de structure où les membres ne sont pas nommés.

[source, rust]
----
struct ColorRGB(i32, i32, i32);
let color = ColorRGB(255, 0, 0);

// On peut utiliser .0 .1 pour nommer les champs
println!("red channel = {}", color.0); 

// On peut aussi déconstruire la structure avec du pattern matching
let ColorRGB(r, g, b) = color; 
----

== Enum
    - Les types `Enum` sont des types disjoints.

[source, rust]
----
    enum Variant {
        Rien,
        Nombre(i32),
        Texte(String),
    }

    let v1: Variant = Variant::Rien;
    let v2: Variant = Variant::Nombre(42);
    let v3: Variant = Variant::Texte(String::from("Hello"));

----

    - Ici `Variant` peut contenir au choix un entier signé, une chaîne ou rien du tout. 
    - Chaque instance ne peut avoir qu'un seul des types à la fois.


== Pattern matching

- Le _pattern matching_ est très pratique pour manipuler les types `Enum`

[source, rust]
----
fn affiche(v: Variant) {
    match v {
        Variant::Rien => println!("Le variant est vide"),
        Variant::Nombre(n) => println!("Le variant contient le nombre {}", n),
        Variant::Texte(s) => println!("Le variant contient le texte {}", s),
    }
}
----

== Gestion des exceptions: std::Option<T>

- En C/C++ on représente souvent l'absence de valeur par un pointeur `nullptr`.
- Cet usage est cause de nombreuses erreurs difficiles à détecter, c'est pourquoi Rust interdit les références nulles.
- Rust utilise le type Enum avec deux variants 
** `None` qui représente l'absence de valeur
** `Some(T)` qui représente une valeur de type `T` (`T` est un type générique quelconque)

== Exemple: std::Option<T>

[source, rust]
----
fn racine(n : f64) -> Option<f64> {
    if n > 0.0 {
        Some(n.sqrt())
    } else {
        None
    }
}

racine(25.0);  // -> Some(5.0)
racine(-25.0); // -> None 

if let Some(r) = racine(25) {
    ...
} else {
    ...
}

// panique si None
let v : f64 = racine(25.0).unwrap(); 
let v : f64 = racine(25.0).expect("erreur: racine d'un nombre négatif"); 
----

== std::Result<T,E>

[source, rust]
----
enum Result<T, E> {
    Ok(T),
    Err(E)
}
----

- `Result` est semblable à une option mais permet d'encoder une erreur de type `E`.
- Il est possible de convertir un `Result` en `Option` avec `res.ok()` (et inversement avec `opt.ok_or(err)`).

== std::Result<T,E>

- Contrairement aux Options, un `Result` doit toujours être utilisé.
- Le compilateur génère un avertissement si un `Result` n'est pas consommé.

[source, rust]
----
use std::fs::File;

fn main() {
    let r : Result<File, std::io::Error> = File::open("hello.txt");

    let f : File = match r {
        Ok(fichier) => fichier,
        Err(erreur) => panic!("Erreur d'ouverture: {:?}", erreur),
    };
}
----

== Gestion fine d'erreurs

[source, rust]
----
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(fichier) => fichier,
        Err(erreur) => match erreur.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Erreur de création du fichier : {:?}", e),
            },
            autre_erreur => {
                panic!("Erreur d'ouverture du fichier : {:?}", autre_erreur)
            }
        },
    };
}
----

== Raccourci avec expect

[source, rust]
----
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").expect("Échec à l'ouverture de hello.txt");
}
----

== Propagation d'Erreurs

- Vos propres fonctions peuvent retourner des erreurs

[source, rust]
----
fn lire_fichier() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(fichier) => fichier,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
----

== Opérateur ?

- Écrire du code qui propage les erreurs est fastidieux
- L'opérateur ? peut-être utilisé dans les fonctions qui retournent `Result` pour en faciliter l'écriture

[source, rust]
----
use std::fs::File;
use std::io;
use std::io::Read;

fn lire_fichier() -> Result<String, io::Error> {
    let mut s = String::new();

    // À chaque utilisation de ? si une erreur se produit, 
    // celle-ci est directement retournée et on sort de la fonction
    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}
----